name: weave
description: "A unified, accessibility-first collaboration client built with Flutter."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^3.3.1
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  go_router: ^14.0.0
  shared_preferences: ^2.3.0
  flutter_appauth: ^12.0.0
  flutter_secure_storage: ^10.0.0
  matrix: ^6.2.0
  flutter_vodozemac: ^0.5.0
  flutter_web_auth_2: ^4.1.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.5.0
  riverpod_generator: ^4.0.3
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
