pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { mavenCentral() }
}

rootProject.name = 'weave-orchestration'
include 'weave-application-core',
        'weave-data-core',
        'weave-files-core',
        'weave-persistence-jpa',
        'weave-runtime-provider-adapters',
        'weave-runtime-security-adapters',
        'infra',
        'server',
        'weave-mcp-server',
        'weave-product-e2e'
