create table weave_audit_events (
    sequence_id bigint generated by default as identity primary key,
    tenant_id varchar(160) not null,
    context_id varchar(255),
    actor_ref varchar(255) not null,
    source_ref varchar(255) not null,
    action varchar(120) not null,
    occurred_at_utc timestamp with time zone not null,
    idempotency_key varchar(255) not null,
    redaction_level varchar(80) not null,
    payload_json text not null,
    constraint uq_weave_audit_events_idempotency
        unique (tenant_id, idempotency_key)
);
