create table weave_chat_conversations (
    tenant_id varchar(160) not null,
    context_id varchar(160) not null,
    conversation_id varchar(160) not null,
    title varchar(512) not null,
    conversation_kind varchar(64) not null,
    open_to_workspace boolean not null,
    lifecycle_state varchar(32) not null,
    encryption_mode varchar(128) not null,
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, conversation_id)
);

create table weave_chat_memberships (
    tenant_id varchar(160) not null,
    conversation_id varchar(160) not null,
    identity_issuer varchar(512) not null,
    actor_ref varchar(255) not null,
    member_role varchar(32) not null,
    membership_state varchar(32) not null,
    invited_at_utc timestamp with time zone,
    joined_at_utc timestamp with time zone,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, conversation_id, identity_issuer, actor_ref),
    foreign key (tenant_id, conversation_id)
        references weave_chat_conversations (tenant_id, conversation_id) on delete cascade
);

create table weave_chat_events (
    sequence_value bigint generated by default as identity,
    tenant_id varchar(160) not null,
    conversation_id varchar(160) not null,
    event_id varchar(255) not null,
    sender_issuer varchar(512) not null,
    sender_ref varchar(255) not null,
    event_kind varchar(32) not null,
    content_json text not null,
    occurred_at_utc timestamp with time zone not null,
    delivery_state varchar(32) not null,
    redacted boolean not null,
    primary key (tenant_id, conversation_id, event_id),
    foreign key (tenant_id, conversation_id)
        references weave_chat_conversations (tenant_id, conversation_id) on delete cascade
);

create table weave_chat_operations (
    tenant_id varchar(160) not null,
    context_id varchar(160) not null,
    operation_id varchar(96) not null,
    operation_type varchar(48) not null,
    identity_issuer varchar(512) not null,
    actor_ref varchar(255) not null,
    conversation_id varchar(160) not null,
    canonical_object_id varchar(255) not null,
    northbound_transaction_id varchar(160) not null,
    provider_transaction_id varchar(160) not null,
    provider_alias_intent varchar(255),
    payload_digest varchar(64) not null,
    operation_state varchar(32) not null,
    attempt_count integer not null,
    last_error_code varchar(96),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, operation_id),
    unique (tenant_id, context_id, identity_issuer, actor_ref, operation_type, conversation_id, northbound_transaction_id)
);

create table weave_chat_outbox (
    tenant_id varchar(160) not null,
    operation_id varchar(96) not null,
    operation_type varchar(48) not null,
    payload_json text not null,
    provider_transaction_id varchar(160) not null,
    outbox_state varchar(32) not null,
    attempt_count integer not null,
    next_attempt_at_utc timestamp with time zone,
    last_error_code varchar(96),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, operation_id),
    foreign key (tenant_id, operation_id)
        references weave_chat_operations (tenant_id, operation_id) on delete cascade
);

create table weave_chat_provider_mappings (
    tenant_id varchar(160) not null,
    provider_key varchar(64) not null,
    object_type varchar(32) not null,
    canonical_object_id varchar(768) not null,
    provider_ref varchar(768),
    mapping_intent_ref varchar(768),
    provider_source_version varchar(255),
    mapping_state varchar(32) not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, provider_key, object_type, canonical_object_id)
);

create table weave_chat_bridge_ledger (
    tenant_id varchar(160) not null,
    ledger_id varchar(96) not null,
    provider_key varchar(64) not null,
    direction varchar(32) not null,
    provider_transaction_id varchar(255),
    provider_event_ref varchar(768),
    canonical_object_id varchar(255),
    source_version varchar(255),
    ledger_state varchar(32) not null,
    observed_at_utc timestamp with time zone not null,
    primary key (tenant_id, ledger_id)
);

create table weave_chat_appservice_transactions (
    provider_key varchar(64) not null,
    homeserver_transaction_id varchar(255) not null,
    payload_digest varchar(64) not null,
    transaction_state varchar(32) not null,
    event_count integer not null,
    duplicate_count integer not null,
    received_at_utc timestamp with time zone not null,
    completed_at_utc timestamp with time zone,
    primary key (provider_key, homeserver_transaction_id)
);

create table weave_chat_quarantine (
    tenant_id varchar(160) not null,
    quarantine_id varchar(96) not null,
    provider_key varchar(64) not null,
    correlation_hash varchar(64) not null,
    reason_code varchar(96) not null,
    observed_at_utc timestamp with time zone not null,
    primary key (tenant_id, quarantine_id)
);

create table weave_chat_read_receipts (
    tenant_id varchar(160) not null,
    conversation_id varchar(160) not null,
    identity_issuer varchar(512) not null,
    actor_ref varchar(255) not null,
    event_id varchar(255) not null,
    read_at_utc timestamp with time zone not null,
    primary key (tenant_id, conversation_id, identity_issuer, actor_ref)
);

create table weave_matrix_revoked_sessions (
    session_hash varchar(64) not null primary key,
    revoked_at_utc timestamp with time zone not null,
    expires_at_utc timestamp with time zone not null
);

create table weave_matrix_identity_projection (
    tenant_id varchar(160) not null,
    identity_issuer varchar(512) not null,
    matrix_user_id varchar(255) not null,
    actor_ref varchar(255) not null,
    authorization_principal_ref varchar(255) not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, identity_issuer, matrix_user_id),
    unique (tenant_id, identity_issuer, actor_ref)
);

create table weave_chat_changes (
    sequence_value bigint generated by default as identity primary key,
    tenant_id varchar(160) not null,
    conversation_id varchar(160) not null,
    change_kind varchar(64) not null,
    canonical_object_id varchar(255),
    callback_deduplication_key varchar(96),
    occurred_at_utc timestamp with time zone not null
);

create index weave_chat_events_visible_idx
    on weave_chat_events (tenant_id, conversation_id, delivery_state, sequence_value);
create unique index weave_chat_events_sequence_idx
    on weave_chat_events (sequence_value);
create index weave_chat_outbox_pending_idx
    on weave_chat_outbox (outbox_state, next_attempt_at_utc);
create index weave_chat_ledger_provider_event_idx
    on weave_chat_bridge_ledger (provider_key, provider_event_ref);
create unique index weave_chat_mapping_provider_ref_idx
    on weave_chat_provider_mappings (provider_key, object_type, provider_ref);
create unique index weave_chat_mapping_intent_idx
    on weave_chat_provider_mappings (provider_key, object_type, mapping_intent_ref);
create unique index weave_chat_callback_change_idx
    on weave_chat_changes (tenant_id, callback_deduplication_key);
create index weave_matrix_revoked_sessions_expiry_idx
    on weave_matrix_revoked_sessions (expires_at_utc);
create index weave_matrix_identity_projection_actor_idx
    on weave_matrix_identity_projection (tenant_id, identity_issuer, actor_ref);
create index weave_chat_conversations_context_idx
    on weave_chat_conversations (tenant_id, context_id, lifecycle_state);
