-- Fresh baseline area: V001__provider_selection_foundation.sql
create table weave_provider_selections (
    category varchar(80) primary key,
    provider_key varchar(160) not null,
    choice_model varchar(80) not null,
    secret_ref varchar(255),
    selected_by varchar(160) not null,
    selected_at_utc timestamp with time zone not null,
    applied boolean not null,
    support_safe boolean not null,
    migration_dry_run_required boolean not null
);

create table weave_provider_selection_notes (
    category varchar(80) not null,
    note_order integer not null,
    note_text varchar(1024) not null,
    primary key (category, note_order),
    constraint fk_weave_provider_selection_notes
        foreign key (category)
        references weave_provider_selections (category)
        on delete cascade
);

-- Fresh baseline area: V002__product_profile_override_foundation.sql
create table weave_product_profile_overrides (
    primary_identity_key varchar(528) primary key,
    display_name varchar(255),
    avatar varchar(512),
    locale varchar(40),
    timezone varchar(80),
    accessibility_preferences_json text not null,
    profile_visibility varchar(80)
);

-- Fresh baseline area: V003__audit_event_persistence_foundation.sql
create table weave_audit_events (
    sequence_id bigint generated by default as identity primary key,
    tenant_id varchar(160) not null,
    context_id varchar(255),
    actor_ref varchar(255) not null,
    source_ref varchar(255) not null,
    action varchar(120) not null,
    occurred_at_utc timestamp with time zone not null,
    idempotency_key varchar(255) not null,
    redaction_level varchar(80) not null,
    payload_json text not null,
    constraint uq_weave_audit_events_idempotency
        unique (tenant_id, idempotency_key)
);

-- Fresh baseline area: V004__migration_run_evidence_persistence_foundation.sql
create table weave_migration_run_evidence (
    run_id varchar(180) not null,
    domain_key varchar(120) not null,
    lifecycle varchar(80) not null,
    object_counts_json text not null,
    content_hashes_json text not null,
    audit_refs_json text not null,
    artifact_refs_json text not null,
    provider_diagnostics_json text not null,
    identity_mapping_complete boolean not null,
    audit_sink_available boolean not null,
    admin_approved boolean not null,
    recorded_at_utc timestamp with time zone not null,
    expires_at_utc timestamp with time zone,
    primary key (run_id, domain_key)
);

-- Fresh baseline area: V005__device_credential_persistence.sql
create table weave_device_credentials (
    credential_id varchar(160) primary key,
    domain varchar(40) not null,
    tenant_id varchar(160) not null,
    principal_ref varchar(255) not null,
    subject_ref varchar(255) not null,
    username varchar(255) not null,
    client_type varchar(80) not null,
    label varchar(255) not null,
    capabilities_json text not null,
    secret_hash text not null,
    issued_at_utc timestamp with time zone not null,
    expires_at_utc timestamp with time zone not null,
    revoked_at_utc timestamp with time zone,
    constraint ck_weave_device_credential_domain check (domain in ('files', 'calendar'))
);

create index idx_weave_device_credentials_principal
    on weave_device_credentials (domain, principal_ref, issued_at_utc);

-- Fresh baseline area: V006__matrix_e2ee_snapshot_persistence.sql
create table weave_matrix_e2ee_snapshots (
    tenant_id varchar(160) primary key,
    sequence_value bigint not null,
    payload_json text not null,
    updated_at_utc timestamp with time zone not null
);

-- Fresh baseline area: V008__identity_provisioning_intent.sql
create table weave_identity_provisioning_intents (
    intent_id uuid primary key,
    tenant_id varchar(160) not null,
    organization_id varchar(160) not null,
    invited_email varchar(320) not null,
    invited_email_sha256 varchar(64) not null,
    requested_role varchar(32) not null,
    provider_invitation_id varchar(200) unique,
    invited_by_issuer varchar(500) not null,
    invited_by_subject varchar(255) not null,
    audit_correlation varchar(255) not null,
    status varchar(32) not null,
    applied_subject varchar(255),
    failure_code varchar(100),
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index weave_identity_provisioning_pending_email
    on weave_identity_provisioning_intents (tenant_id, organization_id, invited_email_sha256, status);

create table weave_identity_admin_operations (
    organization_id varchar(255) not null,
    idempotency_key varchar(128) not null,
    operation_kind varchar(80) not null,
    request_hash varchar(64) not null,
    status varchar(20) not null,
    response_json varchar(16384),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    primary key (organization_id, idempotency_key)
);

-- Fresh baseline area: V009__canonical_chat_and_synapse_bridge.sql
create table weave_chat_conversations (
    tenant_id varchar(160) not null,
    context_id varchar(160) not null,
    conversation_id varchar(160) not null,
    title varchar(512) not null,
    conversation_kind varchar(64) not null,
    open_to_workspace boolean not null,
    lifecycle_state varchar(32) not null,
    encryption_mode varchar(128) not null,
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, conversation_id)
);

create table weave_chat_memberships (
    tenant_id varchar(160) not null,
    conversation_id varchar(160) not null,
    identity_issuer varchar(512) not null,
    actor_ref varchar(255) not null,
    member_role varchar(32) not null,
    membership_state varchar(32) not null,
    invited_at_utc timestamp with time zone,
    joined_at_utc timestamp with time zone,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, conversation_id, identity_issuer, actor_ref),
    foreign key (tenant_id, conversation_id)
        references weave_chat_conversations (tenant_id, conversation_id) on delete cascade
);

create table weave_chat_events (
    sequence_value bigint generated by default as identity,
    tenant_id varchar(160) not null,
    conversation_id varchar(160) not null,
    event_id varchar(255) not null,
    sender_issuer varchar(512) not null,
    sender_ref varchar(255) not null,
    event_kind varchar(32) not null,
    content_json text not null,
    occurred_at_utc timestamp with time zone not null,
    delivery_state varchar(32) not null,
    redacted boolean not null,
    primary key (tenant_id, conversation_id, event_id),
    foreign key (tenant_id, conversation_id)
        references weave_chat_conversations (tenant_id, conversation_id) on delete cascade
);

create table weave_chat_operations (
    tenant_id varchar(160) not null,
    context_id varchar(160) not null,
    operation_id varchar(96) not null,
    operation_type varchar(48) not null,
    identity_issuer varchar(512) not null,
    actor_ref varchar(255) not null,
    conversation_id varchar(160) not null,
    canonical_object_id varchar(255) not null,
    northbound_transaction_id varchar(160) not null,
    provider_transaction_id varchar(160) not null,
    provider_alias_intent varchar(255),
    payload_digest varchar(64) not null,
    operation_state varchar(32) not null,
    attempt_count integer not null,
    last_error_code varchar(96),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, operation_id),
    unique (tenant_id, context_id, identity_issuer, actor_ref, operation_type, conversation_id, northbound_transaction_id)
);

create table weave_chat_outbox (
    tenant_id varchar(160) not null,
    operation_id varchar(96) not null,
    operation_type varchar(48) not null,
    payload_json text not null,
    provider_transaction_id varchar(160) not null,
    outbox_state varchar(32) not null,
    attempt_count integer not null,
    next_attempt_at_utc timestamp with time zone,
    last_error_code varchar(96),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, operation_id),
    foreign key (tenant_id, operation_id)
        references weave_chat_operations (tenant_id, operation_id) on delete cascade
);

create table weave_chat_provider_mappings (
    tenant_id varchar(160) not null,
    provider_key varchar(64) not null,
    object_type varchar(32) not null,
    canonical_object_id varchar(768) not null,
    provider_ref varchar(768),
    mapping_intent_ref varchar(768),
    provider_source_version varchar(255),
    mapping_state varchar(32) not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, provider_key, object_type, canonical_object_id)
);

create table weave_chat_bridge_ledger (
    tenant_id varchar(160) not null,
    ledger_id varchar(96) not null,
    provider_key varchar(64) not null,
    direction varchar(32) not null,
    provider_transaction_id varchar(255),
    provider_event_ref varchar(768),
    canonical_object_id varchar(255),
    source_version varchar(255),
    ledger_state varchar(32) not null,
    observed_at_utc timestamp with time zone not null,
    primary key (tenant_id, ledger_id)
);

create table weave_chat_appservice_transactions (
    provider_key varchar(64) not null,
    homeserver_transaction_id varchar(255) not null,
    payload_digest varchar(64) not null,
    transaction_state varchar(32) not null,
    event_count integer not null,
    duplicate_count integer not null,
    received_at_utc timestamp with time zone not null,
    completed_at_utc timestamp with time zone,
    primary key (provider_key, homeserver_transaction_id)
);

create table weave_chat_quarantine (
    tenant_id varchar(160) not null,
    quarantine_id varchar(96) not null,
    provider_key varchar(64) not null,
    correlation_hash varchar(64) not null,
    reason_code varchar(96) not null,
    observed_at_utc timestamp with time zone not null,
    primary key (tenant_id, quarantine_id)
);

create table weave_chat_read_receipts (
    tenant_id varchar(160) not null,
    conversation_id varchar(160) not null,
    identity_issuer varchar(512) not null,
    actor_ref varchar(255) not null,
    event_id varchar(255) not null,
    read_at_utc timestamp with time zone not null,
    primary key (tenant_id, conversation_id, identity_issuer, actor_ref)
);

create table weave_matrix_revoked_sessions (
    session_hash varchar(64) not null primary key,
    revoked_at_utc timestamp with time zone not null,
    expires_at_utc timestamp with time zone not null
);

create table weave_matrix_identity_projection (
    tenant_id varchar(160) not null,
    identity_issuer varchar(512) not null,
    matrix_user_id varchar(255) not null,
    actor_ref varchar(255) not null,
    authorization_principal_ref varchar(255) not null,
    updated_at_utc timestamp with time zone not null,
    primary key (tenant_id, identity_issuer, matrix_user_id),
    unique (tenant_id, identity_issuer, actor_ref)
);

create table weave_chat_changes (
    sequence_value bigint generated by default as identity primary key,
    tenant_id varchar(160) not null,
    conversation_id varchar(160) not null,
    change_kind varchar(64) not null,
    canonical_object_id varchar(255),
    callback_deduplication_key varchar(96),
    occurred_at_utc timestamp with time zone not null
);

create index weave_chat_events_visible_idx
    on weave_chat_events (tenant_id, conversation_id, delivery_state, sequence_value);
create unique index weave_chat_events_sequence_idx
    on weave_chat_events (sequence_value);
create index weave_chat_outbox_pending_idx
    on weave_chat_outbox (outbox_state, next_attempt_at_utc);
create index weave_chat_ledger_provider_event_idx
    on weave_chat_bridge_ledger (provider_key, provider_event_ref);
create unique index weave_chat_mapping_provider_ref_idx
    on weave_chat_provider_mappings (provider_key, object_type, provider_ref);
create unique index weave_chat_mapping_intent_idx
    on weave_chat_provider_mappings (provider_key, object_type, mapping_intent_ref);
create unique index weave_chat_callback_change_idx
    on weave_chat_changes (tenant_id, callback_deduplication_key);
create index weave_matrix_revoked_sessions_expiry_idx
    on weave_matrix_revoked_sessions (expires_at_utc);
create index weave_matrix_identity_projection_actor_idx
    on weave_matrix_identity_projection (tenant_id, identity_issuer, actor_ref);
create index weave_chat_conversations_context_idx
    on weave_chat_conversations (tenant_id, context_id, lifecycle_state);

-- Fresh baseline area: V010__chat_ledger_fault_isolation_and_reconciliation.sql
alter table weave_chat_appservice_transactions
    add column semantic_fingerprint_version varchar(64) not null default 'matrix-as-semantic-event-set-v2';
alter table weave_chat_appservice_transactions
    add column semantic_mismatch_count integer not null default 0;
alter table weave_chat_appservice_transactions
    add column semantic_mismatch_hash varchar(64);

alter table weave_chat_quarantine
    add column conversation_id varchar(160);
alter table weave_chat_quarantine
    add column category_code varchar(96) not null default 'unclassified';
alter table weave_chat_quarantine
    add column recoverable boolean not null default false;
alter table weave_chat_quarantine
    add column classifier_version varchar(64) not null default 'matrix-synapse-state-v0';
alter table weave_chat_quarantine
    add column lifecycle_state varchar(32) not null default 'rejected';
alter table weave_chat_quarantine
    add column attempt_count integer not null default 0;
alter table weave_chat_quarantine
    add column max_attempts integer not null default 3;
alter table weave_chat_quarantine
    add column last_attempt_at_utc timestamp with time zone;
alter table weave_chat_quarantine
    add column resolved_at_utc timestamp with time zone;
alter table weave_chat_quarantine
    add column last_outcome_code varchar(96);
alter table weave_chat_quarantine
    add column private_homeserver_transaction_id varchar(255);
alter table weave_chat_quarantine
    add column private_provider_event_ref varchar(768);
alter table weave_chat_quarantine
    add column private_provider_room_ref varchar(768);
alter table weave_chat_quarantine
    add column private_normalized_event_json text;

alter table weave_chat_quarantine
    add constraint weave_chat_quarantine_lifecycle_chk
    check (lifecycle_state in ('pending', 'reconciled', 'rejected', 'superseded'));
alter table weave_chat_quarantine
    add constraint weave_chat_quarantine_attempts_chk
    check (attempt_count >= 0 and max_attempts > 0 and attempt_count <= max_attempts);

create index weave_chat_quarantine_scope_idx
    on weave_chat_quarantine (provider_key, tenant_id, conversation_id, lifecycle_state);

-- Fresh baseline area: V011__agent_runtime_control_foundation.sql
create table weave_agent_runtime_cells (
    record_id uuid primary key,
    organization_ref varchar(255) not null,
    person_ref varchar(255) not null,
    member_issuer varchar(500) not null,
    member_subject varchar(255) not null,
    cell_ref varchar(255) not null unique,
    workload_issuer varchar(500) not null,
    workload_subject varchar(255) not null,
    workload_client_id varchar(255) not null,
    workload_authentication_method varchar(64) not null,
    workload_credential_ref varchar(1000) not null,
    entitlement_state varchar(32) not null,
    entitlement_revision varchar(255) not null,
    desired_state varchar(32) not null,
    observed_state varchar(32) not null,
    runtime_profile_id varchar(255),
    runtime_profile_hash varchar(71),
    workspace_revision varchar(255) not null,
    workspace_manifest_ref varchar(1000) not null,
    runtime_state_store_ref varchar(1000) not null,
    fencing_epoch bigint not null default 0 check (fencing_epoch >= 0),
    lease_id uuid,
    lease_expires_at timestamp with time zone,
    version bigint not null default 0 check (version >= 0),
    audit_ref varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint weave_agent_runtime_person_unique unique (organization_ref, person_ref),
    constraint weave_agent_runtime_workload_subject_unique unique (workload_issuer, workload_subject),
    constraint weave_agent_runtime_workload_client_unique unique (workload_issuer, workload_client_id),
    constraint weave_agent_runtime_profile_pair check (
        (runtime_profile_id is null and runtime_profile_hash is null)
        or (runtime_profile_id is not null and runtime_profile_hash is not null)
    ),
    constraint weave_agent_runtime_lease_pair check (
        (lease_id is null and lease_expires_at is null)
        or (lease_id is not null and lease_expires_at is not null)
    )
);

create index weave_agent_runtime_reconcile
    on weave_agent_runtime_cells (desired_state, observed_state, lease_expires_at);

create table weave_agent_runtime_profiles (
    profile_hash varchar(71) primary key,
    profile_id varchar(255) not null unique,
    cell_ref varchar(255) not null,
    organization_ref varchar(255) not null,
    person_ref varchar(255) not null,
    payload text not null,
    selected_key_id varchar(255) not null,
    issued_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    revoked_at timestamp with time zone,
    revocation_code varchar(100),
    created_at timestamp with time zone not null,
    constraint weave_agent_runtime_profile_cell_fk foreign key (cell_ref)
        references weave_agent_runtime_cells (cell_ref),
    constraint weave_agent_runtime_profile_hash_format check (
        char_length(profile_hash) = 71 and profile_hash like 'sha256:%'
    ),
    constraint weave_agent_runtime_profile_expiry check (expires_at > issued_at),
    constraint weave_agent_runtime_profile_revocation_pair check (
        (revoked_at is null and revocation_code is null)
        or (revoked_at is not null and revocation_code is not null)
    )
);

create index weave_agent_runtime_profile_cell
    on weave_agent_runtime_profiles (cell_ref, expires_at, revoked_at);

create table weave_agent_runtime_profile_signatures (
    profile_hash varchar(71) not null,
    key_id varchar(255) not null,
    protected_header text not null,
    signature text not null,
    created_at timestamp with time zone not null,
    primary key (profile_hash, key_id),
    constraint weave_agent_runtime_profile_signature_fk foreign key (profile_hash)
        references weave_agent_runtime_profiles (profile_hash)
);

create table weave_agent_runtime_commands (
    organization_ref varchar(255) not null,
    person_ref varchar(255) not null,
    idempotency_key varchar(128) not null,
    command varchar(64) not null,
    status varchar(32) not null,
    cell_ref varchar(255) not null,
    runtime_version bigint,
    audit_ref varchar(255) not null,
    failure_code varchar(100),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    primary key (organization_ref, person_ref, idempotency_key),
    constraint weave_agent_runtime_command_key_length check (char_length(idempotency_key) between 16 and 128)
);

-- Fresh baseline area: V012__agent_runtime_governance_facts.sql
create table weave_agent_runtime_entitlements (
    record_id uuid primary key,
    entitlement_ref varchar(255) not null unique,
    entitlement_revision varchar(71) not null unique,
    organization_ref varchar(255) not null,
    person_ref varchar(255) not null,
    member_issuer varchar(500) not null,
    member_subject varchar(255) not null,
    source_provider varchar(64) not null,
    source_group_ref varchar(71) not null,
    capability_revision varchar(71) not null,
    entitlement_state varchar(32) not null,
    effective_at timestamp with time zone not null,
    last_observed_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    revocation_ref varchar(255),
    revoked_at timestamp with time zone,
    audit_ref varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint weave_agent_runtime_entitlement_hashes check (
        char_length(entitlement_ref) = 76 and entitlement_ref like 'entitlement:%'
        and char_length(entitlement_revision) = 71 and entitlement_revision like 'sha256:%'
        and char_length(source_group_ref) = 71 and source_group_ref like 'sha256:%'
        and char_length(capability_revision) = 71 and capability_revision like 'sha256:%'
    ),
    constraint weave_agent_runtime_entitlement_times check (
        last_observed_at >= effective_at and expires_at > last_observed_at
    ),
    constraint weave_agent_runtime_entitlement_revocation_pair check (
        (entitlement_state = 'ENTITLED' and revocation_ref is null and revoked_at is null)
        or (entitlement_state = 'REVOKED' and revocation_ref is not null and revoked_at is not null)
    )
);

create index weave_agent_runtime_entitlement_current
    on weave_agent_runtime_entitlements (organization_ref, person_ref, last_observed_at desc);

create table weave_agent_runtime_audit_correlations (
    record_id uuid primary key,
    correlation_ref varchar(255) not null unique,
    organization_ref_hash varchar(71) not null,
    person_ref_hash varchar(71) not null,
    keycloak_ref_hash varchar(71),
    orchestrator_ref_hash varchar(71),
    openclaw_ref_hash varchar(71),
    matrix_ref_hash varchar(71),
    mcp_ref_hash varchar(71),
    domain_audit_ref_hash varchar(71),
    occurred_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    constraint weave_agent_runtime_correlation_link check (
        keycloak_ref_hash is not null or orchestrator_ref_hash is not null
        or openclaw_ref_hash is not null or matrix_ref_hash is not null
        or mcp_ref_hash is not null or domain_audit_ref_hash is not null
    ),
    constraint weave_agent_runtime_correlation_format check (
        char_length(correlation_ref) = 76 and correlation_ref like 'correlation:%'
        and char_length(organization_ref_hash) = 71 and organization_ref_hash like 'sha256:%'
        and char_length(person_ref_hash) = 71 and person_ref_hash like 'sha256:%'
        and (keycloak_ref_hash is null or (char_length(keycloak_ref_hash) = 71 and keycloak_ref_hash like 'sha256:%'))
        and (orchestrator_ref_hash is null or (char_length(orchestrator_ref_hash) = 71 and orchestrator_ref_hash like 'sha256:%'))
        and (openclaw_ref_hash is null or (char_length(openclaw_ref_hash) = 71 and openclaw_ref_hash like 'sha256:%'))
        and (matrix_ref_hash is null or (char_length(matrix_ref_hash) = 71 and matrix_ref_hash like 'sha256:%'))
        and (mcp_ref_hash is null or (char_length(mcp_ref_hash) = 71 and mcp_ref_hash like 'sha256:%'))
        and (domain_audit_ref_hash is null or (char_length(domain_audit_ref_hash) = 71 and domain_audit_ref_hash like 'sha256:%'))
    )
);

create table weave_agent_runtime_revocations (
    record_id uuid primary key,
    revocation_ref varchar(255) not null unique,
    organization_ref varchar(255) not null,
    person_ref varchar(255) not null,
    reason_code varchar(100) not null,
    reason_ref_hash varchar(71) not null,
    actor_ref_hash varchar(71) not null,
    effective_at timestamp with time zone not null,
    entitlement_ref varchar(255) not null,
    entitlement_revision varchar(71) not null,
    cell_ref varchar(255) not null,
    profile_hash varchar(71),
    workload_ref_hash varchar(71) not null,
    audit_correlation_ref varchar(255) not null,
    created_at timestamp with time zone not null,
    constraint weave_agent_runtime_revocation_formats check (
        char_length(revocation_ref) = 75 and revocation_ref like 'revocation:%'
        and char_length(reason_ref_hash) = 71 and reason_ref_hash like 'sha256:%'
        and char_length(actor_ref_hash) = 71 and actor_ref_hash like 'sha256:%'
        and char_length(entitlement_revision) = 71 and entitlement_revision like 'sha256:%'
        and char_length(workload_ref_hash) = 71 and workload_ref_hash like 'sha256:%'
        and char_length(audit_correlation_ref) = 76 and audit_correlation_ref like 'correlation:%'
        and (profile_hash is null or (char_length(profile_hash) = 71 and profile_hash like 'sha256:%'))
    ),
    constraint weave_agent_runtime_revocation_entitlement_fk foreign key (entitlement_ref)
        references weave_agent_runtime_entitlements (entitlement_ref),
    constraint weave_agent_runtime_revocation_cell_fk foreign key (cell_ref)
        references weave_agent_runtime_cells (cell_ref),
    constraint weave_agent_runtime_revocation_correlation_fk foreign key (audit_correlation_ref)
        references weave_agent_runtime_audit_correlations (correlation_ref)
);

create index weave_agent_runtime_revocation_person
    on weave_agent_runtime_revocations (organization_ref, person_ref, effective_at desc);

alter table weave_agent_runtime_cells
    add constraint weave_agent_runtime_cell_entitlement_fk foreign key (entitlement_revision)
        references weave_agent_runtime_entitlements (entitlement_revision);

-- Fresh baseline area: V013__agent_runtime_external_state.sql
create table weave_agent_runtime_state_heads (
    runtime_state_store_ref varchar(1000) primary key,
    organization_ref varchar(255) not null,
    person_ref varchar(255) not null,
    cell_ref varchar(255) not null unique,
    current_generation bigint not null default 0 check (current_generation >= 0),
    current_generation_ref varchar(81),
    version bigint not null default 0 check (version >= 0),
    audit_ref varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint weave_agent_runtime_state_head_generation_pair check (
        (current_generation = 0 and current_generation_ref is null)
        or (current_generation > 0 and current_generation_ref is not null)
    )
);

create table weave_agent_runtime_state_generations (
    generation_ref varchar(81) primary key,
    runtime_state_store_ref varchar(1000) not null,
    generation bigint not null check (generation > 0),
    previous_generation bigint not null check (previous_generation >= 0),
    runtime_profile_hash varchar(71) not null,
    idempotency_key varchar(128) not null,
    encryption_algorithm varchar(64) not null,
    wrapping_key_ref varchar(128) not null,
    wrapped_data_key bytea not null,
    nonce bytea not null,
    plaintext_bytes bigint not null check (plaintext_bytes >= 0),
    ciphertext_bytes bigint not null check (ciphertext_bytes >= 16),
    chunk_count integer not null check (chunk_count > 0),
    audit_ref varchar(255) not null,
    committed_at timestamp with time zone not null,
    constraint weave_agent_runtime_state_generation_store_fk foreign key (runtime_state_store_ref)
        references weave_agent_runtime_state_heads (runtime_state_store_ref),
    constraint weave_agent_runtime_state_generation_number_unique unique (
        runtime_state_store_ref, generation
    ),
    constraint weave_agent_runtime_state_generation_idempotency_unique unique (
        runtime_state_store_ref, idempotency_key
    ),
    constraint weave_agent_runtime_state_generation_hash check (
        char_length(runtime_profile_hash) = 71 and runtime_profile_hash like 'sha256:%'
    ),
    constraint weave_agent_runtime_state_generation_key_length check (
        char_length(idempotency_key) between 16 and 128
    )
);

alter table weave_agent_runtime_state_heads
    add constraint weave_agent_runtime_state_head_current_fk foreign key (current_generation_ref)
        references weave_agent_runtime_state_generations (generation_ref);

create table weave_agent_runtime_state_chunks (
    generation_ref varchar(81) not null,
    chunk_ordinal integer not null check (chunk_ordinal >= 0),
    ciphertext bytea not null,
    primary key (generation_ref, chunk_ordinal),
    constraint weave_agent_runtime_state_chunk_generation_fk foreign key (generation_ref)
        references weave_agent_runtime_state_generations (generation_ref)
);

create table weave_agent_runtime_state_deletions (
    organization_ref varchar(255) not null,
    person_ref varchar(255) not null,
    cell_ref varchar(255) not null,
    runtime_state_store_ref varchar(1000) not null,
    idempotency_key varchar(128) not null,
    deleted_generation_count bigint not null check (deleted_generation_count >= 0),
    audit_ref varchar(255) not null,
    completed_at timestamp with time zone not null,
    primary key (organization_ref, person_ref, idempotency_key),
    constraint weave_agent_runtime_state_deletion_key_length check (
        char_length(idempotency_key) between 16 and 128
    )
);

create index weave_agent_runtime_state_generation_committed
    on weave_agent_runtime_state_generations (runtime_state_store_ref, committed_at desc);

-- Fresh baseline area: V014__durable_operation_intent_and_outbox.sql
create table weave_operation_intents (
    operation_ref varchar(255) primary key,
    intent_version varchar(64) not null,
    idempotency_key varchar(128) not null,
    organization_ref varchar(255) not null,
    actor_kind varchar(32) not null,
    person_ref varchar(255) not null,
    subject_ref varchar(255),
    cell_ref varchar(255),
    client_ref varchar(255),
    profile_revision bigint,
    fencing_epoch bigint,
    domain_key varchar(80) not null,
    projection_kind varchar(32) not null,
    projection_value_1 varchar(255) not null,
    projection_value_2 varchar(255) not null,
    projection_value_3 varchar(255),
    action_digest varchar(71) not null,
    canonical_arguments_digest varchar(71) not null,
    object_refs_json text not null,
    policy_revision varchar(255) not null,
    entitlement_revision varchar(255) not null,
    provider_binding_revision bigint not null,
    intent_state varchar(32) not null,
    initial_outbox_ref varchar(255) not null,
    provider_correlation_hash varchar(71),
    reconciliation_attempts integer not null default 0,
    reconciliation_max_attempts integer not null default 5,
    reconciliation_outcome varchar(40),
    reconciliation_last_attempt_at_utc timestamp with time zone,
    reconciliation_lease_until_utc timestamp with time zone,
    reconciliation_result_digest varchar(71),
    result_digest varchar(71),
    audit_ref varchar(255),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    constraint uq_weave_operation_intent_idempotency unique (organization_ref, idempotency_key),
    constraint chk_weave_operation_actor check (
        (actor_kind = 'human' and subject_ref is not null and cell_ref is null and client_ref is null
            and profile_revision is null and fencing_epoch is null)
        or
        (actor_kind = 'weaver-workload' and subject_ref is null and cell_ref is not null and client_ref is not null
            and profile_revision > 0 and fencing_epoch > 0)
    ),
    constraint chk_weave_operation_state check (
        intent_state in ('CREATED', 'DISPATCHING', 'AMBIGUOUS', 'RECONCILING', 'SUCCEEDED', 'DENIED', 'FAILED')),
    constraint chk_weave_operation_projection check (
        projection_kind in ('protocol', 'admin-api', 'mcp', 'internal')),
    constraint chk_weave_operation_binding_revision check (provider_binding_revision > 0),
    constraint chk_weave_operation_reconciliation_attempts check (
        reconciliation_attempts >= 0 and reconciliation_attempts <= reconciliation_max_attempts),
    constraint chk_weave_operation_terminal check (
        intent_state not in ('SUCCEEDED', 'DENIED', 'FAILED') or (result_digest is not null and audit_ref is not null))
);

create index weave_operation_reconciliation_idx
    on weave_operation_intents (intent_state, reconciliation_lease_until_utc, updated_at_utc);

create table weave_operation_outbox (
    sequence_id bigint generated by default as identity primary key,
    outbox_ref varchar(255) not null unique,
    operation_ref varchar(255) not null,
    event_type varchar(120) not null,
    payload_json text not null,
    delivery_state varchar(32) not null,
    attempt_count integer not null,
    next_attempt_at_utc timestamp with time zone,
    created_at_utc timestamp with time zone not null,
    delivered_at_utc timestamp with time zone,
    constraint fk_weave_operation_outbox_intent foreign key (operation_ref)
        references weave_operation_intents (operation_ref),
    constraint chk_weave_operation_outbox_state check (delivery_state in ('PENDING', 'DELIVERING', 'DELIVERED', 'FAILED')),
    constraint chk_weave_operation_outbox_attempts check (attempt_count >= 0)
);

create index weave_operation_outbox_delivery_idx
    on weave_operation_outbox (delivery_state, next_attempt_at_utc, sequence_id);

-- Fresh baseline area: V015__provider_binding_and_private_mapping.sql
create table weave_provider_bindings (
    organization_ref varchar(255) not null,
    domain_key varchar(80) not null,
    binding_revision bigint not null,
    adapter_key varchar(160) not null,
    configuration_ref varchar(255) not null,
    binding_state varchar(32) not null,
    active_slot boolean,
    activated_at_utc timestamp with time zone not null,
    primary key (organization_ref, domain_key, binding_revision),
    constraint chk_weave_provider_binding_revision check (binding_revision > 0),
    constraint chk_weave_provider_binding_state check (binding_state in ('ACTIVE', 'RETIRED', 'REVOKED')),
    constraint chk_weave_provider_binding_active_slot check (
        (binding_state = 'ACTIVE' and active_slot = true)
        or (binding_state <> 'ACTIVE' and active_slot is null)),
    constraint uq_weave_provider_binding_active unique (organization_ref, domain_key, active_slot)
);

create table weave_provider_object_mappings (
    organization_ref varchar(255) not null,
    domain_key varchar(80) not null,
    binding_revision bigint not null,
    canonical_object_id varchar(255) not null,
    provider_object_ref varchar(1024) not null,
    provenance varchar(255) not null,
    first_observed_at_utc timestamp with time zone not null,
    last_observed_at_utc timestamp with time zone not null,
    primary key (organization_ref, domain_key, binding_revision, canonical_object_id),
    constraint fk_weave_provider_mapping_binding foreign key
        (organization_ref, domain_key, binding_revision)
        references weave_provider_bindings (organization_ref, domain_key, binding_revision),
    constraint uq_weave_provider_mapping_private_ref unique
        (organization_ref, domain_key, binding_revision, provider_object_ref)
);

create index weave_provider_mapping_observed_idx
    on weave_provider_object_mappings (organization_ref, domain_key, binding_revision, last_observed_at_utc);

-- Fresh baseline area: V016__files_canonical_metadata_and_locks.sql
create table weave_files_objects (
    organization_ref varchar(255) not null,
    space_ref varchar(255) not null,
    file_id varchar(255) not null,
    canonical_path varchar(2048) not null,
    object_kind varchar(32) not null,
    byte_size bigint not null,
    media_type varchar(255),
    modified_at_utc timestamp with time zone,
    hidden boolean not null,
    version_token varchar(1024),
    content_digest varchar(71),
    provider_binding_revision bigint not null,
    lifecycle_state varchar(32) not null,
    observed_at_utc timestamp with time zone not null,
    primary key (organization_ref, space_ref, file_id),
    constraint uq_weave_files_canonical_path unique (organization_ref, space_ref, canonical_path),
    constraint chk_weave_files_object_kind check (object_kind in ('FILE', 'COLLECTION')),
    constraint chk_weave_files_byte_size check (byte_size >= 0),
    constraint chk_weave_files_binding_revision check (provider_binding_revision > 0),
    constraint chk_weave_files_lifecycle check (lifecycle_state in ('ACTIVE', 'TOMBSTONED'))
);

create index weave_files_binding_inventory_idx
    on weave_files_objects (organization_ref, provider_binding_revision, lifecycle_state, file_id);

create table weave_file_locks (
    organization_ref varchar(255) not null,
    space_ref varchar(255) not null,
    canonical_path varchar(2048) not null,
    token_digest varchar(71) not null,
    owner_ref varchar(255) not null,
    fence bigint not null,
    expires_at_utc timestamp with time zone not null,
    created_at_utc timestamp with time zone not null,
    released_at_utc timestamp with time zone,
    primary key (organization_ref, space_ref, canonical_path),
    constraint chk_weave_file_lock_fence check (fence > 0),
    constraint chk_weave_file_lock_expiry check (expires_at_utc > created_at_utc)
);

create index weave_file_lock_expiry_idx
    on weave_file_locks (expires_at_utc, released_at_utc);

-- Fresh baseline area: V017__jpa_authority_completion.sql
create table weave_organization_bootstrap (
    organization_id varchar(255) primary key,
    bootstrap_mode varchar(64) not null,
    actor_primary_identity_key varchar(512) not null,
    retained_admin_primary_identity_keys_json text not null,
    bootstrapped_at timestamp with time zone not null
);

-- Fresh baseline area: V018__relational_model_and_optimistic_versions.sql
alter table weave_provider_selections
    add column version bigint not null default 0 check (version >= 0);
alter table weave_product_profile_overrides
    add column version bigint not null default 0 check (version >= 0);
alter table weave_device_credentials
    add column version bigint not null default 0 check (version >= 0);
alter table weave_identity_provisioning_intents
    add column version bigint not null default 0 check (version >= 0);
alter table weave_migration_run_evidence
    add column version bigint not null default 0 check (version >= 0);
alter table weave_matrix_e2ee_snapshots
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_conversations
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_memberships
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_events
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_operations
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_outbox
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_provider_mappings
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_bridge_ledger
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_appservice_transactions
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_quarantine
    add column version bigint not null default 0 check (version >= 0);
alter table weave_chat_read_receipts
    add column version bigint not null default 0 check (version >= 0);
alter table weave_matrix_identity_projection
    add column version bigint not null default 0 check (version >= 0);
alter table weave_agent_runtime_commands
    add column version bigint not null default 0 check (version >= 0);
alter table weave_agent_runtime_profiles
    add column version bigint not null default 0 check (version >= 0);
alter table weave_agent_runtime_entitlements
    add column version bigint not null default 0 check (version >= 0);
alter table weave_provider_bindings
    add column version bigint not null default 0 check (version >= 0);
alter table weave_provider_object_mappings
    add column version bigint not null default 0 check (version >= 0);
alter table weave_files_objects
    add column version bigint not null default 0 check (version >= 0);
alter table weave_file_locks
    add column version bigint not null default 0 check (version >= 0);
alter table weave_operation_intents
    add column version bigint not null default 0 check (version >= 0);
alter table weave_operation_outbox
    add column version bigint not null default 0 check (version >= 0);
alter table weave_organization_bootstrap
    add column version bigint not null default 0 check (version >= 0);

create table weave_person_bindings (
    organization_ref varchar(255) not null,
    issuer varchar(500) not null,
    subject varchar(255) not null,
    person_ref varchar(255) not null,
    created_at_utc timestamp with time zone not null,
    version bigint not null default 0 check (version >= 0),
    primary key (organization_ref, issuer, subject),
    constraint uq_weave_person_binding_person
        unique (organization_ref, person_ref)
);

create index weave_person_binding_lookup_idx
    on weave_person_bindings (organization_ref, person_ref);

create table weave_spaces (
    organization_ref varchar(255) not null,
    space_ref varchar(255) not null,
    lifecycle_state varchar(32) not null,
    version bigint not null default 0 check (version >= 0),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    primary key (organization_ref, space_ref),
    constraint chk_weave_space_lifecycle
        check (lifecycle_state in ('ACTIVE', 'SUSPENDED', 'DELETED'))
);

create table weave_space_memberships (
    organization_ref varchar(255) not null,
    space_ref varchar(255) not null,
    person_ref varchar(255) not null,
    permission_set varchar(255) not null,
    lifecycle_state varchar(32) not null,
    version bigint not null default 0 check (version >= 0),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    primary key (organization_ref, space_ref, person_ref),
    constraint fk_weave_space_membership_space
        foreign key (organization_ref, space_ref)
        references weave_spaces (organization_ref, space_ref),
    constraint fk_weave_space_membership_person_binding
        foreign key (organization_ref, person_ref)
        references weave_person_bindings (organization_ref, person_ref),
    constraint chk_weave_space_membership_lifecycle
        check (lifecycle_state in ('ACTIVE', 'SUSPENDED', 'REVOKED'))
);

create index weave_space_membership_person_idx
    on weave_space_memberships (organization_ref, person_ref, lifecycle_state);

create table weave_portability_plans (
    plan_ref varchar(255) primary key,
    organization_ref varchar(255) not null,
    domain_key varchar(80) not null,
    source_binding_revision bigint not null check (source_binding_revision > 0),
    target_binding_revision bigint not null check (target_binding_revision > 0),
    lifecycle_state varchar(32) not null,
    version bigint not null default 0 check (version >= 0),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    constraint chk_weave_portability_distinct_bindings
        check (source_binding_revision <> target_binding_revision),
    constraint chk_weave_portability_lifecycle
        check (lifecycle_state in (
            'DRAFT', 'DISCOVERING', 'PREFLIGHT', 'DRY_RUN', 'REVIEW_REQUIRED',
            'APPROVED', 'PREPARING', 'COPYING', 'DELTA_SYNC', 'CUTOVER',
            'VERIFYING', 'COMPLETED', 'FAILED', 'ROLLBACK_READY', 'ROLLED_BACK'
        )),
    constraint fk_weave_portability_source_binding
        foreign key (organization_ref, domain_key, source_binding_revision)
        references weave_provider_bindings (organization_ref, domain_key, binding_revision),
    constraint fk_weave_portability_target_binding
        foreign key (organization_ref, domain_key, target_binding_revision)
        references weave_provider_bindings (organization_ref, domain_key, binding_revision)
);

create index weave_portability_reconciliation_idx
    on weave_portability_plans (lifecycle_state, updated_at_utc, plan_ref);

create table weave_portability_fidelity_items (
    plan_ref varchar(255) not null,
    canonical_object_id varchar(255) not null,
    fidelity_class varchar(2) not null,
    disposition varchar(32) not null,
    recorded_at_utc timestamp with time zone not null,
    primary key (plan_ref, canonical_object_id),
    constraint fk_weave_portability_fidelity_plan
        foreign key (plan_ref)
        references weave_portability_plans (plan_ref),
    constraint chk_weave_portability_fidelity_class
        check (fidelity_class in ('F0', 'F1', 'F2', 'F3', 'F4')),
    constraint chk_weave_portability_disposition
        check (disposition in ('PRESERVE', 'TRANSFORM', 'ARCHIVE', 'BLOCK'))
);

create table weave_workspace_revisions (
    organization_ref varchar(255) not null,
    person_ref varchar(255) not null,
    revision bigint not null check (revision > 0),
    manifest_ref varchar(1000) not null,
    manifest_digest varchar(71) not null,
    signature_key_ref varchar(255) not null,
    signature varchar(2048) not null,
    lifecycle_state varchar(32) not null,
    active_slot boolean,
    version bigint not null default 0 check (version >= 0),
    created_at_utc timestamp with time zone not null,
    activated_at_utc timestamp with time zone,
    primary key (organization_ref, person_ref, revision),
    constraint chk_weave_workspace_manifest_digest
        check (char_length(manifest_digest) = 71 and manifest_digest like 'sha256:%'),
    constraint chk_weave_workspace_revision_lifecycle
        check (lifecycle_state in ('DRAFT', 'ACTIVE', 'SUPERSEDED', 'REJECTED')),
    constraint chk_weave_workspace_revision_active_slot
        check (
            (lifecycle_state = 'ACTIVE' and active_slot = true and activated_at_utc is not null)
            or (lifecycle_state <> 'ACTIVE' and active_slot is null)
        ),
    constraint uq_weave_workspace_revision_active
        unique (organization_ref, person_ref, active_slot)
);

create index weave_workspace_revision_history_idx
    on weave_workspace_revisions (organization_ref, person_ref, revision);

create table weave_wake_envelopes (
    organization_ref varchar(255) not null,
    cell_ref varchar(255) not null,
    wake_ref varchar(255) not null,
    event_digest varchar(71) not null,
    outbox_ref varchar(255) not null unique,
    delivery_state varchar(32) not null,
    attempt_count integer not null default 0 check (attempt_count >= 0),
    next_attempt_at_utc timestamp with time zone,
    version bigint not null default 0 check (version >= 0),
    created_at_utc timestamp with time zone not null,
    delivered_at_utc timestamp with time zone,
    primary key (organization_ref, cell_ref, wake_ref),
    constraint fk_weave_wake_cell
        foreign key (cell_ref)
        references weave_agent_runtime_cells (cell_ref),
    constraint uq_weave_wake_event
        unique (organization_ref, cell_ref, event_digest),
    constraint chk_weave_wake_event_digest
        check (char_length(event_digest) = 71 and event_digest like 'sha256:%'),
    constraint chk_weave_wake_delivery
        check (delivery_state in ('PENDING', 'DELIVERING', 'DELIVERED', 'FAILED')),
    constraint chk_weave_wake_terminal
        check (delivery_state <> 'DELIVERED' or delivered_at_utc is not null)
);

create index weave_wake_delivery_idx
    on weave_wake_envelopes (delivery_state, next_attempt_at_utc, created_at_utc);
