create table weave_operation_intents (
    operation_ref varchar(255) primary key,
    intent_version varchar(64) not null,
    idempotency_key varchar(128) not null,
    organization_ref varchar(255) not null,
    actor_kind varchar(32) not null,
    person_ref varchar(255) not null,
    subject_ref varchar(255),
    cell_ref varchar(255),
    client_ref varchar(255),
    profile_revision bigint,
    fencing_epoch bigint,
    domain_key varchar(80) not null,
    projection_kind varchar(32) not null,
    projection_value_1 varchar(255) not null,
    projection_value_2 varchar(255) not null,
    projection_value_3 varchar(255),
    action_digest varchar(71) not null,
    canonical_arguments_digest varchar(71) not null,
    object_refs_json text not null,
    policy_revision varchar(255) not null,
    entitlement_revision varchar(255) not null,
    provider_binding_revision bigint not null,
    intent_state varchar(32) not null,
    initial_outbox_ref varchar(255) not null,
    provider_correlation_hash varchar(71),
    reconciliation_attempts integer not null default 0,
    reconciliation_max_attempts integer not null default 5,
    reconciliation_outcome varchar(40),
    reconciliation_last_attempt_at_utc timestamp with time zone,
    reconciliation_lease_until_utc timestamp with time zone,
    reconciliation_result_digest varchar(71),
    result_digest varchar(71),
    audit_ref varchar(255),
    created_at_utc timestamp with time zone not null,
    updated_at_utc timestamp with time zone not null,
    constraint uq_weave_operation_intent_idempotency unique (organization_ref, idempotency_key),
    constraint chk_weave_operation_actor check (
        (actor_kind = 'human' and subject_ref is not null and cell_ref is null and client_ref is null
            and profile_revision is null and fencing_epoch is null)
        or
        (actor_kind = 'weaver-workload' and subject_ref is null and cell_ref is not null and client_ref is not null
            and profile_revision > 0 and fencing_epoch > 0)
    ),
    constraint chk_weave_operation_state check (
        intent_state in ('CREATED', 'DISPATCHING', 'AMBIGUOUS', 'RECONCILING', 'SUCCEEDED', 'DENIED', 'FAILED')),
    constraint chk_weave_operation_projection check (
        projection_kind in ('protocol', 'admin-api', 'mcp', 'internal')),
    constraint chk_weave_operation_binding_revision check (provider_binding_revision > 0),
    constraint chk_weave_operation_reconciliation_attempts check (
        reconciliation_attempts >= 0 and reconciliation_attempts <= reconciliation_max_attempts),
    constraint chk_weave_operation_terminal check (
        intent_state not in ('SUCCEEDED', 'DENIED', 'FAILED') or (result_digest is not null and audit_ref is not null))
);

create index weave_operation_reconciliation_idx
    on weave_operation_intents (intent_state, reconciliation_lease_until_utc, updated_at_utc);

create table weave_operation_outbox (
    sequence_id bigint generated by default as identity primary key,
    outbox_ref varchar(255) not null unique,
    operation_ref varchar(255) not null,
    event_type varchar(120) not null,
    payload_json text not null,
    delivery_state varchar(32) not null,
    attempt_count integer not null,
    next_attempt_at_utc timestamp with time zone,
    created_at_utc timestamp with time zone not null,
    delivered_at_utc timestamp with time zone,
    constraint fk_weave_operation_outbox_intent foreign key (operation_ref)
        references weave_operation_intents (operation_ref),
    constraint chk_weave_operation_outbox_state check (delivery_state in ('PENDING', 'DELIVERING', 'DELIVERED', 'FAILED')),
    constraint chk_weave_operation_outbox_attempts check (attempt_count >= 0)
);

create index weave_operation_outbox_delivery_idx
    on weave_operation_outbox (delivery_state, next_attempt_at_utc, sequence_id);
