ARG WEAVE_KEYCLOAK_BASE=quay.io/keycloak/keycloak@sha256:0f198be292568439d700cdbfb893e69a6009bb43a94a06a945b1d3d506c76b13
FROM ${WEAVE_KEYCLOAK_BASE} AS builder

COPY --chown=1000:1000 keycloak-workload-registration-provider/build/libs/weave-workload-client-registration-provider-1.0.0.jar \
    /opt/keycloak/providers/weave-workload-client-registration-provider.jar
RUN /opt/keycloak/bin/kc.sh build --db=postgres

FROM ${WEAVE_KEYCLOAK_BASE}

ARG WEAVE_IMAGE_CREATED=unbound
ARG WEAVE_IMAGE_REVISION=unbound
ARG WEAVE_IMAGE_VERSION=unbound
ARG WEAVE_SPEC_DIGEST=unbound
ARG WEAVE_SBOM_REFERENCE=unbound
ARG WEAVE_PROVENANCE_REFERENCE=unbound

LABEL org.opencontainers.image.title="Weave Keycloak Runtime" \
      org.opencontainers.image.description="Version-pinned Keycloak runtime with the Weave workload client-registration policy provider" \
      org.opencontainers.image.source="https://github.com/masssi164/weave" \
      org.opencontainers.image.revision="${WEAVE_IMAGE_REVISION}" \
      org.opencontainers.image.version="${WEAVE_IMAGE_VERSION}" \
      org.opencontainers.image.created="${WEAVE_IMAGE_CREATED}" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.vendor="Weave" \
      com.massimotter.weave.spec-digest="${WEAVE_SPEC_DIGEST}" \
      com.massimotter.weave.module="keycloak-runtime" \
      com.massimotter.weave.runtime-user="1000:1000" \
      com.massimotter.weave.dependency-platform="keycloak-26.7-client-policy-spi" \
      com.massimotter.weave.provider-id="weave-workload-client-registration-enforcer" \
      com.massimotter.weave.sbom-reference="${WEAVE_SBOM_REFERENCE}" \
      com.massimotter.weave.provenance-reference="${WEAVE_PROVENANCE_REFERENCE}"

COPY --from=builder --chown=1000:1000 /opt/keycloak/ /opt/keycloak/
USER 1000:1000
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
