FROM python:3.14.1-alpine@sha256:b80c82b1a282283bd3e3cd3c6a4c895d56d1385879c8c82fa673e9eb4d6d4aa5

COPY sanitizer-requirements.txt /tmp/sanitizer-requirements.txt
RUN python3 -m pip install \
      --disable-pip-version-check \
      --no-cache-dir \
      --only-binary=:all: \
      --require-hashes \
      --requirement /tmp/sanitizer-requirements.txt \
    && rm /tmp/sanitizer-requirements.txt \
    && addgroup -S -g 65532 weave \
    && adduser -S -D -H -u 65532 -G weave weave

USER 65532:65532
WORKDIR /opt/weave/keycloak
ENTRYPOINT ["python3"]
