services:
  caddy:
    extra_hosts:
      - host.docker.internal:host-gateway

  keycloak:
    depends_on: !reset {}
    command:
      - start-dev
    environment:
      KC_DB: dev-file
    secrets: !override
      - keycloak-bootstrap-admin-password

  synapse:
    extra_hosts:
      - host.docker.internal:host-gateway

  mailpit:
    environment:
      MP_SMTP_REQUIRE_TLS: "false"
