import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';

import '../../integration_test/helpers/live_test_tls.dart';

void main() {
  group('live test TLS trust', () {
    test(
      'disabled extra root uses platform trust even with an invalid value',
      () {
        final trust = LiveTestTlsTrust.fromEncodedRoot(
          enabled: false,
          encodedRoot: 'not-base64',
        );

        expect(trust.usesExtraRoot, isFalse);
        expect(trust.createSecurityContext(), isA<SecurityContext>());
      },
    );

    test('enabled valid certificate creates an additive trust context', () {
      final trust = _testTrust();

      expect(trust.usesExtraRoot, isTrue);
      expect(trust.createSecurityContext(), isA<SecurityContext>());
      expect(
        LiveTestTlsTrust.fromEncodedRoot(
          enabled: true,
          encodedRoot: _testServerCertificatePemBase64,
        ).usesExtraRoot,
        isTrue,
      );
    });

    test(
      'enabled missing, malformed, private, and oversized roots fail closed',
      () {
        final invalidRoots = <String>[
          '',
          'not-base64',
          base64Encode(utf8.encode('not a certificate')),
          _testServerPrivateKeyPemBase64,
          base64Encode(Uint8List(maximumLiveTestRootPemBytes + 1)),
          base64Encode(
            utf8.encode(
              '-----BEGIN CERTIFICATE-----\nZm9v\n'
              '-----END CERTIFICATE-----\n',
            ),
          ),
        ];

        for (final encodedRoot in invalidRoots) {
          expect(
            () => LiveTestTlsTrust.fromEncodedRoot(
              enabled: true,
              encodedRoot: encodedRoot,
            ),
            throwsA(isA<LiveTestTlsConfigurationException>()),
          );
        }
      },
    );

    test(
      'native TLS enforces both trusted chain and requested hostname',
      () async {
        expect(HttpOverrides.current, isNull);
        final serverContext = SecurityContext()
          ..useCertificateChainBytes(
            base64Decode(_networkTestServerChainPemBase64),
          )
          ..usePrivateKeyBytes(
            base64Decode(_networkTestServerPrivateKeyPemBase64),
          );
        final server = await HttpServer.bindSecure(
          InternetAddress.loopbackIPv4,
          0,
          serverContext,
        );
        final subscription = server.listen((request) async {
          request.response.write('trusted');
          await request.response.close();
        });
        addTearDown(() async {
          await subscription.cancel();
          await server.close(force: true);
        });
        final uri = Uri.parse('https://localhost:${server.port}/health');

        final untrustedClient = HttpClient(
          context: SecurityContext(withTrustedRoots: false),
        );
        addTearDown(() => untrustedClient.close(force: true));
        await expectLater(
          _status(untrustedClient, uri),
          throwsA(isA<HandshakeException>()),
        );

        final networkTrust = LiveTestTlsTrust.fromEncodedRoot(
          enabled: true,
          encodedRoot: _networkTestCaCertificatePemBase64,
        );
        final trustedClient = HttpClient(
          context: networkTrust.createSecurityContext(
            baseContext: SecurityContext(withTrustedRoots: false),
          ),
        );
        addTearDown(() => trustedClient.close(force: true));
        expect(await _status(trustedClient, uri), HttpStatus.ok);

        final wrongHostnameClient = createLiveTestHttpClient(
          trust: networkTrust,
        );
        wrongHostnameClient.findProxy = (_) => 'DIRECT';
        wrongHostnameClient.connectionFactory =
            (uri, proxyHost, proxyPort) async {
              return ConnectionTask.fromSocket(
                Socket.connect(InternetAddress.loopbackIPv4, server.port),
                () {},
              );
            };
        addTearDown(() => wrongHostnameClient.close(force: true));
        await expectLater(
          _status(
            wrongHostnameClient,
            Uri.parse('https://wrong.weave.test:${server.port}/health'),
          ),
          throwsA(anyOf(isA<HandshakeException>(), isA<HttpException>())),
        );
      },
    );

    test('live HTTP helpers contain no certificate-verification bypass', () {
      final helperFiles = <String>[
        'integration_test/helpers/live_oidc_test_driver.dart',
        'integration_test/helpers/live_test_tls.dart',
        'integration_test/helpers/test_http_overrides.dart',
      ];

      for (final path in helperFiles) {
        expect(
          File(path).readAsStringSync(),
          isNot(contains('badCertificateCallback')),
          reason: '$path must rely on native chain and hostname validation.',
        );
      }
    });
  });
}

LiveTestTlsTrust _testTrust() {
  return LiveTestTlsTrust.fromEncodedRoot(
    enabled: true,
    encodedRoot: _testCaCertificatePemBase64,
  );
}

Future<int> _status(HttpClient client, Uri uri) async {
  final request = await client.getUrl(uri);
  final response = await request.close();
  await response.drain<void>();
  return response.statusCode;
}

// Test-only CA, leaf certificate, and key for the loopback TLS server. The
// leaf carries SANs for 127.0.0.1 and localhost. None is production material.
const _testCaCertificatePemBase64 =
    'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNekNDQWh1Z0F3SUJBZ0lVUWVaLzZiVmtwWk1zcUw5c1g1VkdEWEswNVhRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lURWZNQjBHQTFVRUF3d1dWMlZoZG1VZ2JHbDJaU0JVVEZNZ2RHVnpkQ0JEUVRBZUZ3MHlOakEzTVRJeApNak00TkROYUZ3MHpOakEzTURreE1qTTRORE5hTUNFeEh6QWRCZ05WQkFNTUZsZGxZWFpsSUd4cGRtVWdWRXhUCklIUmxjM1FnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNZMUVmVTR4UkMKelV3UUJKc01pZjV1NitVTy9SSmZZQlhPaHB6SnRDalJ1RFhDZzljei9STjFqMHdYL3QzVXJlYXhxa3JUOWtxWApJWVZLWmNaeUsrVHM5VTNWbXVkS0JzQlRKSFJoVmdIVktHM1N3L2N2eThMbEVCZDhmK2lKR2szeDlId1REQm9vCkpPMFV4RzBEN1RYakVPY3NocjhWMStrZkVJTW5sRzk4a0dwSTZvbE9Dd3RraFJ6RGtCSE5wTFNUbm9lcnBHd1YKQnZYSndkd09YcFhGeWdDN2hIdWphOFZHRGNZSkd5dXRiMDNaT0RPRU9pM0JlbTJzVldyVmo1bmI5OCtoU1ZNUgpaaXh2YTJGbUVHTTV4NVlrMEFpRlhFOTFobTdnZFZUNGROUTZ3YXBJUUVBaXBLbDdNSUFDVDFib2dEK2JML3dQClc4bmd3WCt1SUw3ZEFnTUJBQUdqWXpCaE1CMEdBMVVkRGdRV0JCVDlEbzhVaTRCck1HdUZ0MEZEeEZ2dVpUOFAKSGpBZkJnTlZIU01FR0RBV2dCVDlEbzhVaTRCck1HdUZ0MEZEeEZ2dVpUOFBIakFQQmdOVkhSTUJBZjhFQlRBRApBUUgvTUE0R0ExVWREd0VCL3dRRUF3SUJCakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBa3ZtSWhvdHVDaDd3CkpvQmlLSTFsMmJSZHBMTndUeFM4QXpyWHByOWpWSzdORUlaN3lhTk1xNk91em1tc29xaDJlM1hmL2hNa2RsTlgKRHV1cTdWL3RvRnZyMzdyMWhHb2dQdHZpajAzTVlhUzhQZ2Y4RFFiamRQQ3V2bkpJNzZ3SkdDbCtHdnRaUk9aWQpqbnZVK1pVUVp6QkRjbmZWZDVpeC9EbmNYeWNwc0dETmUxR01senZtUForcTZtZWlqaStxZitqVDJ5VjhqVU9JCjBtbUQwOWxxbVVtT1k0QjBIeXlzUmFVTG9FRlRqdHJYZmhCbzd1Z2tpNWduZXRoa1hNR1lVclhMODM1QVVUMHkKQW9IWWhLZkZTay9EMldKM1o4WFVudzFYWUhheGxtL3ZEQzJSQW1mNnRPaXY1cUp2NjArbG9xTlNTNXBSU3JQLwp4TThPVTJScFZRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=';

const _testServerCertificatePemBase64 =
    'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo2Z0F3SUJBZ0lVZU1lRjg2S1hFbGluNWFCcFFqTkUrUmxLLzlBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lURWZNQjBHQTFVRUF3d1dWMlZoZG1VZ2JHbDJaU0JVVEZNZ2RHVnpkQ0JEUVRBZUZ3MHlOakEzTVRJeApNak00TkRSYUZ3MHpOakEzTURreE1qTTRORFJhTUJReEVqQVFCZ05WQkFNTUNXeHZZMkZzYUc5emREQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMZHV1ZThXQVJ0cG9DZUpGZ1dYQ3JhQWFlMzIKR3UvbVpHMk5abG9xamlQZHovL0NXbEtleXNjaXBlSk5kcVFkOFduL1dFb3U0UHJZTzlJY0tjNUhnSmtLMjdOOQpxWGVrbXpSZnRFbDByZWppa21TV0NpRy83VUY4K1pObTl3c0J2VWZoRkN5aFJlVUh0TTZoOEpiMk5yUURQSzFICmd0L1Jobk1hOWxnbEtCNEFqc1pKNHFZTlJXZzRmTEJSMWlNZG1xZjdXTXJWMEdJODF1dDA3ekVybUE5OWRZZXMKTFd1Y1k2QXZTZG9zMVQ1VFoyVVBzL0NubVBFMWxiQjd6ek8vZ1hEeFpNU1VPMVJpdXZhcy9oSVNmaHBERFBSNwowcTVjUUNqdjdWYXk3Y2VzTS9aV2xqbk9ST0Vab3ZlczFtNFBlcEdxZC83TE4vaytvQzlYM1R0Tkp4MENBd0VBCkFhT0JrakNCanpBYUJnTlZIUkVFRXpBUmh3Ui9BQUFCZ2dsc2IyTmhiR2h2YzNRd0RBWURWUjBUQVFIL0JBSXcKQURBT0JnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0hRWURWUjBPQkJZRQpGRlJvR0lGSlpLMWVKQktSbWJCeUxYTS9Majk1TUI4R0ExVWRJd1FZTUJhQUZQME9qeFNMZ0dzd2E0VzNRVVBFClcrNWxQdzhlTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBeTRmT1BtbEZrSnR1U0ZnRzNwRFZ6NUt3ZkF4WnAKYjJIb010WkxhUUxGcWVQaXowTEp2Uk0wL2ViYW8zSDJKLytzemFZaC8yanJ2alc1a1haVStuQ08wQkh1Vm5rNApRZ2xrS1hnMEV6ZWg5TWIxL2VTZUFiUUZ4VW1hbXdDcVpJRjcyNlkwSkU1bW0xWEZjUjVMK1pEcm9NbmVCb2RPClJycTlIVTJXRHdjUWhKYXBVMi9LNzNDM01pVGtvQUVqZlpZVjFsYy9SSXAwM1N4UFBOVGVBZnlxVGpiTFBuSHIKeGRPckdjdytSUlRhZHVqbFdIRzg4a0tDc3ZVR3Y2ZlJmc1ZscktHS0hsTGkxVk5wUjkxZnVtUzJHVmF5L0VmSAowenVNYitvSmpBNzlVVFprbTQxeXYyclpOVEdibWlGNC9hdFVHV0l0TGcyTmhrejFzM1FsTVc2LwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==';

const _testServerPrivateKeyPemBase64 =
    'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzNicm52RmdFYmFhQW4KaVJZRmx3cTJnR250OWhydjVtUnRqV1phS280ajNjLy93bHBTbnNySElxWGlUWGFrSGZGcC8xaEtMdUQ2MkR2UwpIQ25PUjRDWkN0dXpmYWwzcEpzMFg3UkpkSzNvNHBKa2xnb2h2KzFCZlBtVFp2Y0xBYjFINFJRc29VWGxCN1RPCm9mQ1c5amEwQXp5dFI0TGYwWVp6R3ZaWUpTZ2VBSTdHU2VLbURVVm9PSHl3VWRZakhacW4rMWpLMWRCaVBOYnIKZE84eEs1Z1BmWFdIckMxcm5HT2dMMG5hTE5VK1UyZGxEN1B3cDVqeE5aV3dlODh6djRGdzhXVEVsRHRVWXJyMgpyUDRTRW40YVF3ejBlOUt1WEVBbzcrMVdzdTNIckRQMlZwWTV6a1RoR2FMM3JOWnVEM3FScW5mK3l6ZjVQcUF2ClY5MDdUU2NkQWdNQkFBRUNnZ0VBQmhmTUszNlo2Mm12RTMzcUh3eHAxcFYzbGJUU3dOWTlhRm5GdnE1aWxvRm4KTGpoZktYMHpadXlNWjlsREVCcTFVUTlWa2IwL2Z0OHFlWVZNa1A4N244ejVicWhmQXN3VFBCd0c2YjdyVnJtQQp1NDB6NlkydHpJZVVza3B3eGhmc01vZUhWT3lVZHF1WTljeUxEd1BZM2V3U3pjc1VaMC9YRnNFY2EzdFM0WU5pCjg4YmJNS1RmMVY3TmZROHNYWkxkbzNjbG9peDVlQlluK2VnUmFNN1NUVXdTMlgwYzBvQS96MG1qSnNPUnlYbE0KUENGRTVHUjFsRzNOU3Y0NmVlYnpEZXBBdWZ5bTZOdHFiUCtxeSt2WGNQZGRIeHZRZ2ZzVUxNZmJJWXNoK0s0SgpaRmZac2I2NHFDUG9uTVlZSkcwYmxpbXRtd2l0TEhLeUN0NndBb2pqZHdLQmdRRHc2M1RhbWVJY1AzWmV0aGt3CnJuaXZaaVZtc3RnVmtyaDBES2F4VU1CQU1OdEtHUy9QZFVPTjZzSXhtTVNMNlpZNHJZMm9mdjJERWRYMHhsSGwKb2NFUzdPRTVQUHhPVm4xajJ5N3liSy96ejN1ZUFiMmx2RndGR2FLOUR3N2NESlgyRFBVLzJYbTFNK2RMWkJKbgpkb2VnSCtWSDM4b3duY0Mramg0ZU0yOXZYd0tCZ1FEQzZoVnJwRUJGdC9jaW80Zys2b0pxQmt3ZTFtVFB2R2VJCkxVd2hBbEc5ckNPNzdkOTBST1R6dWl2dHltSXdXUmVJUnNvWU8wSGZmQk5hQnViNm5sT3lGNVBwSVFETTZPelMKVUVWNExkRnducFEraGtFTWhpUW1oU1Nzci9GMWd2Zk1obzZxelAxS2pvVHY0VjdNSTBKMy9wWTJDL0dFUVh1SwowcDBHY2hUSEF3S0JnUURjV1M1K2hjSmx2YkdnL0lKYm9TZm1uTkZXZGZybStGUFdhSC9KcTZhNnp6U3lPQWtmCmdRd3hiK2IvZjg4OGZIK1dCVDZNUHVIVmtHbVZRQkpGcWNVeWJ3K3J6MWlndWNCanBXUHgvSENOMlZZaDlVdWsKbTN1NmVuRDY1QnZlTFhDM0k3RG9IaHVRSFJIT1JaQURxMGh1cnQyQStIRXdPQWpEQUs4UlJsQUVsd0tCZ1FDego4dHN0MHFtSDlFelVqUGZuWmloYTdFOXdsT3pqb1FSUWc4bHFIRE1ORXBTM0Z1aWE5bFFOOUU1RUxmbXl1ejN2CmtiTlk1YlJ1T0tYQkV1aENidFBFY3VJYWRGN0J6elY5QWFEeFVCT3hqcVk4aDBRYzVPY1JMUkRyNFUvaDlyVUIKL1NSUDZncmF2M05aNTg3V1ZxTXlGemZrMCtmNCsxK3NqYjlzeVB3SHN3S0JnQW9yWmlubGNSUnlFVmJ6bUoyagpxQnViQTQ0TDgzcU1US3B0OEVxVUZpSlZNUFY1STIzN3RPWXkrRkhPQk1HY1I2NC93aEthT3dpUWVmVnkxdnJ2CjJPMW5MRVh0NGd0TFB0bUQ3QzMydEJOSC9QQlBCcHdnOU51SnU0UEdHRStTTHBjcEkySjIrYnp2dk9JV3RPa2gKSjhEOUltRGVzcmo0TDhwR1gwMEdtaUhpCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K';

// The native-network fixture uses a complete root/intermediate/leaf chain.
// Its leaf expires 2028-10-09 and must be rotated before that date.
const _networkTestCaCertificatePemBase64 =
    'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFZTVJZd0ZBWURWUVFEREExeWIyOTAKWVhWMGFHOXlhWFI1TUI0WERUSTJNRGN4TWpFeU5EY3dPVm9YRFRNMk1EY3dPVEV5TkRjd09Wb3dHREVXTUJRRwpBMVVFQXd3TmNtOXZkR0YxZEdodmNtbDBlVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBUFEwNjFib1E3M1BFODFzek1hdW5PSEdPaElBc0srb3NjNVhMNnVnaWcxQ3plcTdVNEVhZ2ZjV042YmoKYmc5dGNDMUxiOVdxdjFySG9MSTFsNVEwb01wUFdiaDZkOHI3NlhqV29rYkc2MmQ4dlN3NEVvdVlRcm82RVRJTgpQeGpPVVlmWXBwZWlpWTk4cmVPNjI5ZHBXclRIYkRHb2t4a256YkdmRTRkOVoxb25reExWaFFDWUYwVG9MK3plClpZU0M0NCs4dHZsTTloVE9MRFpyNzg1YWZOSWYvOHp1Sk85VGFPUEk0Q0pkVnRhZWVNc0lPaWRoSUJNZTIvVFQKN2k4TlIvekVHTk5SVFFseGlENkppbzkwOFY1ZlpUcXd3UkJLS0FSakdQdnZRUndUNTZaQTdyN3BLVzVad0pvVQprTlVrRm5xam5nSlVjMDBxb0lDbTZta2ZlNmNDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkQ0T3NPc2pvWWg1CkgvQ1dBNkZMN3VPMlhObjRNQjhHQTFVZEl3UVlNQmFBRkQ0T3NPc2pvWWg1SC9DV0E2Rkw3dU8yWE5uNE1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVdKY3dKeWorYndPZUp4ZHhRZApIZmMvbjBWRnA5Q2lHWldyTEtWTFZNdlpEVTdZN0pqK3lSa3VWWkx1QVdZdzBDSTdRaUJOdVYrQnU4YjM5UG1nCnBudlMwdDQyV2U5ellFR3F6NUtTQk1kZ1pYbjhBdUsxR3NMTis3Ti8wdUY3N2psZExLV1M0WGNiOEhJMjFVOTMKUlhiMGlWZkI5cWVrSko4cHhRVHBVcndyUVZIcldNVHB2OEdBSy9LK0l4UFhHMkxmUlQ2TlR3emlueTUzN0swOQpBbzBaOEVnRUhhcDZCZWVQUHZzbzRFcEM5TXY3Q0JpS1lJdnU4S2djUXJpUjhqZUNud2w2TEU5SU5WZi9wTGdrCk91ZlFmUDRmdzJZeFhjamo1bW8yYXNQYzdjMEdNcW8vTDZrVEZrQW1BSTdRREZsTjBGLyt6VTBaUzNSSktTMlcKT1ZFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==';

const _networkTestServerChainPemBase64 =
    'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFnTVI0d0hBWURWUVFEREJWcGJuUmwKY20xbFpHbGhkR1ZoZFhSb2IzSnBkSGt3SGhjTk1qWXdOekV5TVRJME9ERTNXaGNOTWpneE1EQTVNVEkwT0RFMwpXakFVTVJJd0VBWURWUVFEREFsc2IyTmhiR2h2YzNRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDdUhxaXo4Skc3ZGRwM3VrRFFUeXVwSU1NNlhKVFppcS9iTHZSVlVKVjBWR3NReDRQTXNxT3cKbFFQb0pBQklBRVE1dncwOGNkUjRmV3RhbC9yRXhZd3pDaEE3NXhmbmx5MlJMSzAyZmpmdmZqZWdvWUJZQ2lregorc2ZTek8yL2FveVdObWFNS2lnQzRLN1FEcE5LSEY1cjVRWW5UdEIwTjlLUDZSVDk0WEpaMmNPT3VxWS8xa3FCCjlBUDJZdk5tbWpkSTJHcWZoQUMxcmJic2VvY1hsU1VkRktHbUgxQTdTSzZOZktaWDB1clVXTHE1czJsOUtWKzMKSzVWUElPNUhIRFZ4MHQ0VFBycXYvcDN5TzNUbkFhRytwRXZyK1E1aUNrMDRhcXRIMUp3UUYycHdCQ0x5Q0wrTgptOFVQQU1Oay9uUHNTbnduYWpaZUIzS0Z1L3o4NGczYkFnTUJBQUdqZ2JRd2diRXdQQVlEVlIwUkJEVXdNNElKCmJHOWpZV3hvYjNOMGdna3hNamN1TUM0d0xqR0NBem82TVljRWZ3QUFBWWNRQUFBQUFBQUFBQUFBQUFBQUFBQUEKQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlEreWpjTkhkeXJUZk14a3ZrRTFzMEF2TkY3WGpBZgpCZ05WSFNNRUdEQVdnQlNpNDNkeVhlTGtBQXQ4WDErK1I1ZEhXd2k3dnpBT0JnTlZIUThCQWY4RUJBTUNBNmd3CkV3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTXV0clhzZE9uWE8KNXJMYmpvVE5YdFgvRlhnU1ZkVlJMMGU3Q3l6NFlmYm16RldLSkNGS0FhMWttUlVCUUNteFVKenM3YTFGNnhwdwp5YUxpaWNCbWVaRkJBQTZVWlhwRms1ZVMrYzU3NUJIbFAvdkpaQ0ZqcnhnMEJ3aU1pN2F5WkxIcW5GcVVvN1A3CjZpS2tlZ2FlQXB4UHVOY1R1M3Uxb0h3eGZFSjdMbXJ4MUpHT01uTVRkSVE2bXUzSWU2MFZYblhGVHozUW9YZ28KMjlBbW8wRDNsdUx4dFJ2aWFnT3E4WW0wa1RsbkRaYzZNa3JKMkE0MU9JclZ1UWpkM1NqT2Ruc0k5dk1teUhuQQppQiswU2RJM1ZKTXFOSkNhaWpsQXdtY1RtYWRVazh1K2V5MUZTczRxVzJFcTN2czl0aEV3UEhLQ3NvWHJSRWhTCnlqQ05DRTdCbXQ4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlETGpDQ0FoYWdBd0lCQWdJQkFqQU5CZ2txaGtpRzl3MEJBUXNGQURBWU1SWXdGQVlEVlFRRERBMXliMjkwCllYVjBhRzl5YVhSNU1CNFhEVEkyTURjeE1qRXlORGN3T1ZvWERUTTJNRGN3T1RFeU5EY3dPVm93SURFZU1Cd0cKQTFVRUF3d1ZhVzUwWlhKdFpXUnBZWFJsWVhWMGFHOXlhWFI1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBek5qL3NMRk5nVXdPRHRJSnAwRW1RNEx0RUErb0RrWDVnWlN2S3BvK0xqblN3TEdJCkdNOEI5ZG16Q2k1aVJDczMvNWdmOEZyQTZYRlFZbG9jdWZhWi9sMXlGMFBreEs5RWE0dzdOdlMxTlo0eTNJcE4Kcm1KQytGaGg5OUs5YWpvdkg4WkJLdytHL1pMUUFTS2dEWDFGK05MN2hCUlFUaUF3L3VBU1dWcnJFeWlIS1M0cgpJTFUxWDgzNGZlc2prTE9rUHAwRVRYT1ZoTlNITlI0bmlPc0RpL3g1SnZKRWlsdGJzUW5aeVVRZnR6MmtzaXhtCm81bTVvWXVaNm5mTzMwVlpjc0RlMDRnM3hIK2hONnM1c2MvbXV1V2lUY3U4ckwxbTBPOEpJQ24wVHBaQVl5TUYKTktmb3pPRHpvc1pTcE5XUzFWWmJNS2YyTm5vZmdhZDhCNzR3a3dJREFRQUJvM3N3ZVRBU0JnTlZIUk1CQWY4RQpDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNpNDNkeVhlTGtBQXQ4WDErK1I1ZEhXd2k3dnpBZkJnTlZIU01FCkdEQVdnQlErRHJEckk2R0llUi93bGdPaFMrN2p0bHpaK0RBT0JnTlZIUThCQWY4RUJBTUNBZ1F3RXdZRFZSMGwKQkF3d0NnWUlLd1lCQlFVSEF3RXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSG5XUjhFV1Znb1kxa1VVUHJscApPWVlsM0U2d2crS01NK014czdXSXFJMHAvNG1JRXQxM2VRczhNNkJqOVgxZXJ2VGNoQnU0U0VNS3BQak05Mk94CmtReU96UlZaem5DRGFycmdFbDc2QVFUWTFWTDBZTGJ6cDdLeFNqWWRJVHZrYStFWnlzbTVRM3k3YUt1OVVzamoKOUs0Z2RqVFkySFZrTEdNTkZsNGhaUWUrWVNyOE1uUWRDME4xUVBrRnNkcWVIcUx1bEtXOGNyR2dFTnJnbURDWAo3R2ZCT0t3WlBFSEI4NkIyRGo5eXNkTEVOdG16Y2hEY0wya0ptY21Sam1EQjJpdFNKNFJxVHc5UnVTZys5M0tUCmt1U2lXdGcxU3k1bVF6U0pqV1VEUk1WUzc1MkZoNkF2SFROUmRZZ3g0aEV6SGRMeXVKeXJzSkFDL09pQ2EySkUKYW1jPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDL2pDQ0FlYWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBWU1SWXdGQVlEVlFRRERBMXliMjkwCllYVjBhRzl5YVhSNU1CNFhEVEkyTURjeE1qRXlORGN3T1ZvWERUTTJNRGN3T1RFeU5EY3dPVm93R0RFV01CUUcKQTFVRUF3d05jbTl2ZEdGMWRHaHZjbWwwZVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQVBRMDYxYm9RNzNQRTgxc3pNYXVuT0hHT2hJQXNLK29zYzVYTDZ1Z2lnMUN6ZXE3VTRFYWdmY1dONmJqCmJnOXRjQzFMYjlXcXYxckhvTEkxbDVRMG9NcFBXYmg2ZDhyNzZYaldva2JHNjJkOHZTdzRFb3VZUXJvNkVUSU4KUHhqT1VZZllwcGVpaVk5OHJlTzYyOWRwV3JUSGJER29reGtuemJHZkU0ZDlaMW9ua3hMVmhRQ1lGMFRvTCt6ZQpaWVNDNDQrOHR2bE05aFRPTERacjc4NWFmTklmLzh6dUpPOVRhT1BJNENKZFZ0YWVlTXNJT2lkaElCTWUyL1RUCjdpOE5SL3pFR05OUlRRbHhpRDZKaW85MDhWNWZaVHF3d1JCS0tBUmpHUHZ2UVJ3VDU2WkE3cjdwS1c1WndKb1UKa05Va0ZucWpuZ0pVYzAwcW9JQ202bWtmZTZjQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZENE9zT3Nqb1loNQpIL0NXQTZGTDd1TzJYTm40TUI4R0ExVWRJd1FZTUJhQUZENE9zT3Nqb1loNUgvQ1dBNkZMN3VPMlhObjRNQThHCkExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFXSmN3SnlqK2J3T2VKeGR4UWQKSGZjL24wVkZwOUNpR1pXckxLVkxWTXZaRFU3WTdKait5Umt1VlpMdUFXWXcwQ0k3UWlCTnVWK0J1OGIzOVBtZwpwbnZTMHQ0MldlOXpZRUdxejVLU0JNZGdaWG44QXVLMUdzTE4rN04vMHVGNzdqbGRMS1dTNFhjYjhISTIxVTkzClJYYjBpVmZCOXFla0pKOHB4UVRwVXJ3clFWSHJXTVRwdjhHQUsvSytJeFBYRzJMZlJUNk5Ud3ppbnk1MzdLMDkKQW8wWjhFZ0VIYXA2QmVlUFB2c280RXBDOU12N0NCaUtZSXZ1OEtnY1FyaVI4amVDbndsNkxFOUlOVmYvcExnawpPdWZRZlA0ZncyWXhYY2pqNW1vMmFzUGM3YzBHTXFvL0w2a1RGa0FtQUk3UURGbE4wRi8relUwWlMzUkpLUzJXCk9WRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=';

const _networkTestServerPrivateKeyPemBase64 =
    'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3VIcWl6OEpHN2RkcDMKdWtEUVR5dXBJTU02WEpUWmlxL2JMdlJWVUpWMFZHc1F4NFBNc3FPd2xRUG9KQUJJQUVRNXZ3MDhjZFI0Zld0YQpsL3JFeFl3ekNoQTc1eGZubHkyUkxLMDJmamZ2ZmplZ29ZQllDaWt6K3NmU3pPMi9hb3lXTm1hTUtpZ0M0SzdRCkRwTktIRjVyNVFZblR0QjBOOUtQNlJUOTRYSloyY09PdXFZLzFrcUI5QVAyWXZObW1qZEkyR3FmaEFDMXJiYnMKZW9jWGxTVWRGS0dtSDFBN1NLNk5mS1pYMHVyVVdMcTVzMmw5S1YrM0s1VlBJTzVISERWeDB0NFRQcnF2L3AzeQpPM1RuQWFHK3BFdnIrUTVpQ2swNGFxdEgxSndRRjJwd0JDTHlDTCtObThVUEFNTmsvblBzU253bmFqWmVCM0tGCnUvejg0ZzNiQWdNQkFBRUNnZ0VBRk9HMlo4WVNlWUhtZVI5aGhkbnpmdGdLc2RBZFJkaFNiaDNtZUQ0dTA2eGcKSHJ0ZXZNamJ4V0gwVXYzUStYeEJYUStOa3ljdm9tSks0cXJXdHpjek1OZlBIMFZWWWovZU1NcVpNZ1RYSG50cgpubkcxUmxtMFJxTkNjd1NDcXNjb3p4eFNhMmc1aU53bCt1dS9QRThaLzg4NnBWellDNzFreDVUZUlKM09BZnBmCk1oZWRlenU3bmx4WW5Vb1B2YThnUG84RTFGOHBRalJPTzZ3eHRRUThkUFJRVTZVT0hlZ2ZpOFJPNFdSOXlDLzMKbWFjczNYdTZYMUl3T1RDMG8wSlovSkZSTzNERmN1UHdPKyt6NkxlNmR2cG1rN283ZUtxMEFiMXZlTjMyVE5sRQovbDNOR2VobU5CNm9nSFplS1JCWXNQOTJkQmhDbzJFRm9JZ1ZPaDFEZ1FLQmdRRHAreWczajNBRU5ua1h6TCtjCjBvWmxNWnZKVElBL20xTUVxVkZuZFo4VGk5OHF1V3BBdm1ONUExZ2F3Yjd2UVhsdEJ1eDVlK1F2bFZMWklhOHUKcndQRVZyMzY3UzN5RVNSYmRFTTlDMUhSK2V3ZWljK0JONjlqMDVIWFZReEkxSHBJVUV4eGtiRWhXc2t1aTBJdQowKytua20yRzJiSXZ0T0tEN0VMSUthQ3ptd0tCZ1FDK2dXR3lvMG01cGcvdjhTTWxyNjQ0MmxIZ01pd1VMam5rCndtK0NQYktUZ29iUmtuTlJTMHJPWVB6NHdPTHNzQzhPVTYwUjRTSzE0K3ZMRlRhcmFYRmFobzZpZXhEYU9GYUIKS2RjQUhXZm1JZjlSRnAwa0JIMmNYcldMMWgzUEFwc3g3QWlTOUF4RUZCR2kveE1nUzJkYlhGS2FJOUhYa3dTRgorUitPWGtsU3dRS0JnUUNHRkZGNGZTNndpMUthNjg2Rm5ESTlmTThMN0ZXMW5WbFdXM3gxYi9hSGFlaXBmL1MrClF4dVhkZTRmN3hSdDREUW40UWJUbXNZbzZrVytmVW40MDN1eUlBN2Y0dGdvVmVCaXM5M3Y5ak9kd3J5bXgwdnMKZlM5NVlmeTV5MWV0eUd5R1VkVnNZeE9BekpocW5veC9ieDF2Qmo3VFBwNllMZXg3c29DV1dSeG9yd0tCZ0JlbQphRUtORXZJQk02bE4vbGNIWUZHZWlOdVVYdlNDYUoyRnBlSTlWcFlKZGtNK015SzhmaVR3MVhic096KzIvNkIvCnN0U3RabW0rU2QrRVdxMGRBZjJEQnVJVTlScWlNOXNGSHJQYzhyRVhOMk1SczZCdERrc0RWdlp0Tm5Za2xLKzEKNWJxWW9ZMHlFSjV6bkNRK09DNlhYNG5UT0pIU3BwVWJRRmVrVE9ZQkFvR0JBTWdhK3hzUmZLOWpTS1d5RWFaLwozZ2RRckZGMlRmV0lGdklQbmhreE10WTExMWNPanFqQS9kbk05WUdYVENoMmhpUEVWQklZRTY0eUs4blJpOXhKCnloQTdMeDd5S3Jmb0tSMEtTclhJMkNLNFBLdGIydkVadUFlc2Z4Qk8yUVMrbllyNTJsMFpkODZLY3U0Zk5MTisKdFhkUm9TaElwMGExam5ETjJoODRmVitmCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K';
