#!/usr/bin/env python3
"""Generate Admin Console TypeScript types from the server-owned OpenAPI artifact."""
from __future__ import annotations

import json
import sys
from argparse import ArgumentParser
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / "contracts/openapi/weave-openapi.json"
OUT = ROOT / "admin-console/src/generated/openapi.ts"
ADMIN_PREFIXES = (
    "Admin",
    "CapabilityWhitelist",
    "ChatProviderReplacement",
    "ChatReadiness",
    "IdentityProviderReadiness",
    "ProviderReadiness",
    "ProviderReplacement",
)


def ts_name(name: str) -> str:
    return "Generated" + name


def refs_in(value: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(value, dict):
        ref = value.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
            found.add(ref.split("/")[-1])
        for child in value.values():
            found.update(refs_in(child))
    elif isinstance(value, list):
        for child in value:
            found.update(refs_in(child))
    return found


def select_schema_closure(schemas: dict[str, Any]) -> dict[str, Any]:
    selected = {name for name in schemas if name.startswith(ADMIN_PREFIXES)}
    pending = list(selected)
    while pending:
        name = pending.pop()
        for ref in refs_in(schemas[name]):
            if ref in schemas and ref not in selected:
                selected.add(ref)
                pending.append(ref)
    return {name: schemas[name] for name in sorted(selected)}


def type_for(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return ts_name(schema["$ref"].split("/")[-1])
    if "allOf" in schema:
        return " & ".join(type_for(item) for item in schema["allOf"])
    if "oneOf" in schema or "anyOf" in schema:
        key = "oneOf" if "oneOf" in schema else "anyOf"
        return " | ".join(type_for(item) for item in schema[key])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    schema_type = schema.get("type")
    nullable = False
    if isinstance(schema_type, list):
        nullable = "null" in schema_type
        schema_type = next((t for t in schema_type if t != "null"), None)
    if schema_type == "array":
        result = f"{type_for(schema.get('items'))}[]"
    elif schema_type == "object" or "properties" in schema:
        additional = schema.get("additionalProperties")
        if "properties" not in schema and additional:
            result = f"Record<string, {type_for(additional if isinstance(additional, dict) else {})}>"
        else:
            result = "Record<string, unknown>" if "properties" not in schema else inline_object(schema)
    elif schema_type in {"integer", "number"}:
        result = "number"
    elif schema_type == "boolean":
        result = "boolean"
    elif schema_type == "string":
        result = "string"
    else:
        result = "unknown"
    return f"{result} | null" if nullable else result


def inline_object(schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    parts = []
    for key, value in sorted(schema.get("properties", {}).items()):
        optional = "" if key in required else "?"
        parts.append(f"  {json.dumps(key)}{optional}: {type_for(value)};")
    if schema.get("additionalProperties"):
        parts.append("  [key: string]: unknown;")
    return "{\n" + "\n".join(parts) + "\n}"


def render() -> str:
    document = json.loads(OPENAPI.read_text())
    selected = select_schema_closure(document["components"]["schemas"])
    lines = [
        "// Generated by tools/generate_admin_openapi_types.py from contracts/openapi/weave-openapi.json.",
        "// Do not edit by hand; run ./gradlew generateAdminOpenApiTypes.",
        "",
    ]
    for name, schema in selected.items():
        lines.append(f"export type {ts_name(name)} = {type_for(schema)};")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without changing files when the checked-in TypeScript types are stale",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUT.is_file() or OUT.read_text() != generated:
            print(
                "Admin OpenAPI generated types are stale. "
                "Run ./gradlew generateAdminOpenApiTypes and commit the result.",
                file=sys.stderr,
            )
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generated)
    print(f"Generated {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
